# Generated by Django 5.1.15 on 2026-06-20 16:08

import apps.core.mixins
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('client_name', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=100)),
                ('client_position', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
            bases=(models.Model, apps.core.mixins.TranslatableMixin),
        ),
        migrations.CreateModel(
            name='TestimonialTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('auto_translated', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='testimonials.testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial Translation',
                'verbose_name_plural': 'Testimonial Translations',
                'unique_together': {('testimonial', 'language')},
            },
        ),
    ]
