# Generated by Django 5.1.15 on 2026-06-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('budget_range', models.CharField(choices=[('under_5k', '< 5 000 MAD'), ('5k_20k', '5 000 - 20 000 MAD'), ('20k_50k', '20 000 - 50 000 MAD'), ('50k_100k', '50 000 - 100 000 MAD'), ('over_100k', '> 100 000 MAD'), ('not_specified', 'Non spécifié')], default='not_specified', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé'), ('spam', 'Spam')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_content', models.TextField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies', to=settings.AUTH_USER_MODEL)),
                ('service_interested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='services.service')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
