# Generated by Django 5.1.15 on 2026-06-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=50, unique=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Pages SEO',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TANGER CODE', max_length=100)),
                ('site_email', models.EmailField(default='contact@tangercode.com', max_length=254)),
                ('site_phone', models.CharField(blank=True, default='', max_length=30)),
                ('site_address', models.TextField(blank=True, default='')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('ga4_property_id', models.CharField(blank=True, default='', max_length=50)),
                ('ga4_measurement_id', models.CharField(blank=True, default='', max_length=50)),
                ('google_search_console_verification', models.CharField(blank=True, default='', max_length=100)),
                ('recaptcha_site_key', models.CharField(blank=True, default='', max_length=100)),
                ('recaptcha_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='PageSEOTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=120)),
                ('meta_description', models.TextField(blank=True, default='', max_length=320)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.pageseo')),
            ],
            options={
                'verbose_name': 'Page SEO Translation',
                'verbose_name_plural': 'Page SEO Translations',
                'unique_together': {('page', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SiteConfigTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('footer_description', models.TextField(blank=True, default='')),
                ('whatsapp_message', models.TextField(blank=True, default='')),
                ('seo_default_title', models.CharField(blank=True, default='', max_length=120)),
                ('seo_default_description', models.TextField(blank=True, default='')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.siteconfig')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
            options={
                'verbose_name': 'Site Config Translation',
                'verbose_name_plural': 'Site Config Translations',
                'unique_together': {('config', 'language')},
            },
        ),
    ]
