# Generated by Django 5.1.15 on 2026-06-20 16:08

import apps.core.mixins
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='get_title', unique=True)),
                ('icon', models.CharField(default='code', help_text='Lucide icon name', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'slug'],
            },
            bases=(models.Model, apps.core.mixins.TranslatableMixin),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='technologies/')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('database', 'Database'), ('devops', 'DevOps'), ('design', 'Design')], default='frontend', max_length=20)),
                ('color', models.CharField(default='#0052CC', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='starter', max_length=20)),
                ('price_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_custom_quote', models.BooleanField(default=False)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('revisions_count', models.IntegerField(blank=True, null=True)),
                ('support_days', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='services.service')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['service', 'order'],
            },
            bases=(models.Model, apps.core.mixins.TranslatableMixin),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.technology'),
        ),
        migrations.CreateModel(
            name='PricingTierTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(default='Commander', max_length=50)),
                ('auto_translated', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('pricing_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.pricingtier')),
            ],
            options={
                'verbose_name': 'Pricing Tier Translation',
                'verbose_name_plural': 'Pricing Tier Translations',
                'unique_together': {('pricing_tier', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('short_description', models.TextField(max_length=300)),
                ('long_description', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=120)),
                ('meta_description', models.TextField(blank=True, default='', max_length=320)),
                ('auto_translated', models.BooleanField(default=False)),
                ('last_edited_manually', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Translation',
                'verbose_name_plural': 'Service Translations',
                'unique_together': {('service', 'language')},
            },
        ),
    ]
