# Generated by Django 5.1.15 on 2026-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtiertranslation',
            name='last_edited_manually',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
