# Generated by Django 5.1.15 on 2026-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorytranslation',
            name='auto_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogposttranslation',
            name='last_edited_manually',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogtagtranslation',
            name='auto_translated',
            field=models.BooleanField(default=False),
        ),
    ]
