# Generated by Django 5.1.15 on 2026-06-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('google', 'Google Gemini')], default='claude', max_length=20)),
                ('api_key', models.TextField(help_text='Encrypted at rest with Fernet')),
                ('base_url', models.URLField(blank=True, default='', help_text='Override API base URL')),
                ('model_name', models.CharField(default='claude-3-5-sonnet-20241022', max_length=100)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('temperature', models.FloatField(default=0.3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
            },
        ),
        migrations.CreateModel(
            name='TranslationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('default', 'Texte court (titre, nom)'), ('long_text', 'Texte long (description)'), ('rich_text', 'Texte riche (article, HTML)'), ('list', 'Liste (features)')], default='default', max_length=20)),
                ('prompt_template', models.TextField(help_text='Use {content}, {source_language}, {target_language}, {field_type}')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Translation Prompt',
                'verbose_name_plural': 'Translation Prompts',
            },
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('source_language', models.CharField(max_length=5)),
                ('target_language', models.CharField(max_length=5)),
                ('source_text', models.TextField(help_text='Truncated to 500 chars')),
                ('translated_text', models.TextField(blank=True, default='', help_text='Truncated to 500 chars')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped (manual edit)')], default='success', max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation.aiprovider')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Translation Log',
                'verbose_name_plural': 'Translation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
