# Generated by Django 5.1.15 on 2026-06-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='monthly_cost_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional monthly USD cost cap. Translation is blocked when exceeded.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='model_name',
            field=models.CharField(default='claude-sonnet-4-20250514', max_length=100),
        ),
    ]
