import type { ProjectData } from "./home-data";

export interface ProjectResult {
  value: string;
  label: string;
}

export interface ProjectTestimonial {
  quote: string;
  name: string;
  role: string;
}

export interface ProjectDetail {
  slug: string;
  title: string;
  client: string;
  category: string;
  year: number;
  duration: string;
  tags: string[];
  coverLabel: string;
  defi: string[];
  solution: string[];
  results: ProjectResult[];
  images: string[];
  testimonial: ProjectTestimonial;
  relatedProjects: ProjectData[];
}

export interface PortfolioPageData {
  eyebrow: string;
  title: string;
  subtitle: string;
  lastBreadcrumb: string;
  loadMore: string;
  filters: { key: string; label: string }[];
  projects: ProjectData[];
  details: ProjectDetail[];
}

const frProjects: ProjectData[] = [
  { title: "Atlas Market", client: "Marketplace · Casablanca", category: "ecom", year: 2025, tags: ["Next.js", "Stripe", "Sanity"], slug: "/portfolio/atlas-market" },
  { title: "Medina ERP", client: "Gestion industrielle · Tanger", category: "erp", year: 2025, tags: ["Django", "PostgreSQL", "Docker"], slug: "/portfolio/medina-erp" },
  { title: "RihlaGo", client: "App de voyage · Maroc", category: "mobile", year: 2024, tags: ["Flutter", "Firebase", "Maps"], slug: "/portfolio/rihlago" },
  { title: "Detroit Avocats", client: "Cabinet juridique · Tanger", category: "web", year: 2024, tags: ["Astro", "CMS", "SEO"], slug: "/portfolio/detroit-avocats" },
  { title: "Mizan", client: "SaaS comptable · Rabat", category: "platform", year: 2025, tags: ["React", "Node.js", "AWS"], slug: "/portfolio/mizan" },
  { title: "Zellige Store", client: "Artisanat en ligne · Fes", category: "ecom", year: 2024, tags: ["Shopify", "i18n", "CDN"], slug: "/portfolio/zellige-store" },
  { title: "Cap Spartel", client: "Hotellerie · Tanger", category: "web", year: 2024, tags: ["Next.js", "Booking", "SEO"], slug: "/portfolio/cap-spartel" },
  { title: "SoukConnect", client: "Marketplace B2B · Maroc", category: "platform", year: 2025, tags: ["React", "GraphQL", "Redis"], slug: "/portfolio/soukconnect" },
  { title: "FoodTruck MA", client: "Commande mobile · Tetouan", category: "mobile", year: 2023, tags: ["Flutter", "Stripe", "Maps"], slug: "/portfolio/foodtruck-ma" },
  { title: "Riad Booking", client: "Reservation riads · Marrakech", category: "web", year: 2023, tags: ["Astro", "Calendar", "i18n"], slug: "/portfolio/riad-booking" },
  { title: "GestaPro", client: "Facturation PME · Agadir", category: "erp", year: 2024, tags: ["Django", "PostgreSQL", "BI"], slug: "/portfolio/gestapro" },
  { title: "EduTanger", client: "LMS educatif · Tanger", category: "platform", year: 2025, tags: ["Next.js", "Prisma", "Video"], slug: "/portfolio/edutanger" },
];

const frDetails: ProjectDetail[] = [
  { slug: "atlas-market", title: "Atlas Market", client: "Atlas Retail Group", category: "E-commerce", year: 2025, duration: "4 mois", tags: ["Next.js", "Stripe", "Sanity", "PostgreSQL", "Vercel"], coverLabel: "cover full · Atlas Market", defi: ["Atlas Retail Group souhaitait unifier ses trois enseignes sous une marketplace unique, capable de gerer des milliers de references, plusieurs vendeurs et des pics de trafic pendant les periodes de soldes. L'ancien site, lent et difficile a maintenir, freinait la croissance.", "L'enjeu : livrer une experience d'achat rapide, multilingue (FR/AR) et un back-office permettant aux equipes de gerer le catalogue en toute autonomie."], solution: ["Nous avons reconstruit la plateforme sur Next.js avec un CMS headless (Sanity) et des paiements Stripe. Le rendu cote serveur et un CDN global garantissent des temps de chargement sous la seconde, partout dans le monde."], results: [{ value: "+40%", label: "de ventes en ligne en 3 mois" }, { value: "0.8s", label: "temps de chargement moyen" }, { value: "3\u21921", label: "enseignes unifiees en une marketplace" }], images: ["accueil", "fiche produit", "panier", "checkout", "back-office"], testimonial: { quote: "Un travail d'orfevre. Le site est rapide, magnifique et nos ventes ont bondi de 40 % en trois mois.", name: "Yasmine Bennani", role: "CEO · Atlas Market" }, relatedProjects: [{ title: "Zellige Store", client: "Projet client", category: "ecom", year: 2024, tags: ["Shopify"], slug: "/portfolio/zellige-store" }, { title: "SoukConnect", client: "Projet client", category: "platform", year: 2025, tags: ["React"], slug: "/portfolio/soukconnect" }, { title: "Riad Booking", client: "Projet client", category: "web", year: 2023, tags: ["Astro"], slug: "/portfolio/riad-booking" }] },
  { slug: "medina-erp", title: "Medina ERP", client: "Medina Industries", category: "ERP", year: 2025, duration: "6 mois", tags: ["Django", "PostgreSQL", "Docker", "Redis", "Celery"], coverLabel: "cover full · Medina ERP", defi: ["Medina Industries gerait ses stocks, factures et RH avec des fichiers Excel et plusieurs outils deconnectes. Les erreurs de saisie etaient frequentes et le reporting prenait des jours.", "L'enjeu : centraliser toutes les operations dans un ERP unique, accessible depuis l'usine et le siege, avec des tableaux de bord en temps reel."], solution: ["Nous avons developpe un ERP sur mesure avec Django et PostgreSQL. L'architecture modulaire permet d'ajouter de nouvelles fonctionnalites sans impacter l'existant. Les imports/exports CSV automatisent les echanges avec les partenaires."], results: [{ value: "-60%", label: "d'erreurs de saisie" }, { value: "x3", label: "plus rapide pour les rapports mensuels" }, { value: "100%", label: "des processus centralises" }], images: ["dashboard principal", "gestion stocks", "facturation", "RH", "reporting"], testimonial: { quote: "Notre ERP a transforme notre gestion. Tout est centralise, fluide et enfin comprehensible.", name: "Karim El Fassi", role: "Directeur · Medina Industries" }, relatedProjects: [{ title: "GestaPro", client: "Projet client", category: "erp", year: 2024, tags: ["Django"], slug: "/portfolio/gestapro" }, { title: "Mizan", client: "Projet client", category: "platform", year: 2025, tags: ["React"], slug: "/portfolio/mizan" }, { title: "SoukConnect", client: "Projet client", category: "platform", year: 2025, tags: ["GraphQL"], slug: "/portfolio/soukconnect" }] },
  { slug: "rihlago", title: "RihlaGo", client: "RihlaGo SARL", category: "Mobile", year: 2024, duration: "5 mois", tags: ["Flutter", "Firebase", "Maps", "Notifications"], coverLabel: "cover full · RihlaGo", defi: ["RihlaGo souhaitait proposer une application de voyage complete : decouverte de destinations, reservation d'activites et partage d'itineraires entre voyageurs. Le marche etait domine par des acteurs etrangers sans contenu local.", "L'enjeu : lancer une application iOS et Android en 5 mois avec un contenu riche, une UX fluide et un mode hors-ligne pour les zones sans reseau."], solution: ["Nous avons developpe l'application avec Flutter pour une base de code unique. Firebase gere l'authentification, le stockage des medias et les notifications push. Le mode offline utilise SQLite local avec synchronisation automatique des que la connexion est retablie."], results: [{ value: "15k", label: "telechargements en 3 mois" }, { value: "4.8", label: "etoiles sur les stores" }, { value: "60%", label: "d'utilisation hors-ligne" }], images: ["ecran accueil", "carte interactive", "fiche destination", "reservation", "profil"], testimonial: { quote: "Reactif, precis et force de proposition. L'app mobile a depasse toutes nos attentes.", name: "Sofia Alaoui", role: "Fondatrice · RihlaGo" }, relatedProjects: [{ title: "FoodTruck MA", client: "Projet client", category: "mobile", year: 2023, tags: ["Flutter"], slug: "/portfolio/foodtruck-ma" }, { title: "Atlas Market", client: "Projet client", category: "ecom", year: 2025, tags: ["Next.js"], slug: "/portfolio/atlas-market" }, { title: "Cap Spartel", client: "Projet client", category: "web", year: 2024, tags: ["Booking"], slug: "/portfolio/cap-spartel" }] },
  { slug: "detroit-avocats", title: "Detroit Avocats", client: "Cabinet Detroit", category: "Site web", year: 2024, duration: "2 mois", tags: ["Astro", "CMS", "SEO", "i18n"], coverLabel: "cover full · Detroit Avocats", defi: ["Le cabinet Detroit Avocats avait un site WordPress lent, peu reference et difficile a mettre a jour. Il souhaitait un site professionnel refletant son expertise et attirant des clients corporate.", "L'enjeu : livrer un site statique ultra-rapide avec un CMS facile a utiliser par l'equipe juridique et optimise pour le referencement local."], solution: ["Nous avons migre le site vers Astro avec un CMS headless. Les pages se chargent en moins de 0.5s grace au rendu statique. Le SEO local a ete travaille avec des pages dediees par specialite et ville."], results: [{ value: "0.4s", label: "temps de chargement" }, { value: "+120%", label: "de trafic organique en 6 mois" }, { value: "100/100", label: "score Lighthouse SEO" }], images: ["page accueil", "page equipe", "specialites", "blog", "contact"], testimonial: { quote: "Du conseil au deploiement, un partenaire de confiance. Je recommande sans hesiter.", name: "Omar Tazi", role: "Associe · Detroit Avocats" }, relatedProjects: [{ title: "Cap Spartel", client: "Projet client", category: "web", year: 2024, tags: ["Next.js"], slug: "/portfolio/cap-spartel" }, { title: "Riad Booking", client: "Projet client", category: "web", year: 2023, tags: ["Astro"], slug: "/portfolio/riad-booking" }, { title: "EduTanger", client: "Projet client", category: "platform", year: 2025, tags: ["Next.js"], slug: "/portfolio/edutanger" }] },
  { slug: "mizan", title: "Mizan", client: "Mizan Tech", category: "Plateforme", year: 2025, duration: "5 mois", tags: ["React", "Node.js", "AWS", "Docker"], coverLabel: "cover full · Mizan", defi: ["Mizan Tech developpait un SaaS de comptabilite pour les petites entreprises marocaines. Le defi : respecter les normes comptables locales tout en offrant une interface simple pour des utilisateurs non-comptables.", "L'enjeu : construire une plateforme securisee, conforme a la legislation marocaine, avec des tableaux de bord en temps reel et la generation automatique des declarations fiscales."], solution: ["Nous avons concu l'architecture avec React pour le front-end et Node.js pour l'API. Les donnees sensibles sont chiffrees au repos. Un moteur de regles comptables applique automatiquement les bonnes pratiques selon la legislation marocaine."], results: [{ value: "200+", label: "entreprises utilisatrices actives" }, { value: "99.9%", label: "de disponibilite" }, { value: "-80%", label: "de temps de saisie comptable" }], images: ["dashboard", "saisie comptable", "declarations fiscales", "rapports", "parametres"], testimonial: { quote: "Une plateforme SaaS solide, livree dans les delais. La qualite du code est remarquable.", name: "Leila Mansouri", role: "CTO · Mizan" }, relatedProjects: [{ title: "Medina ERP", client: "Projet client", category: "erp", year: 2025, tags: ["Django"], slug: "/portfolio/medina-erp" }, { title: "GestaPro", client: "Projet client", category: "erp", year: 2024, tags: ["Django"], slug: "/portfolio/gestapro" }, { title: "SoukConnect", client: "Projet client", category: "platform", year: 2025, tags: ["React"], slug: "/portfolio/soukconnect" }] },
  { slug: "zellige-store", title: "Zellige Store", client: "Artisanat Zellige", category: "E-commerce", year: 2024, duration: "3 mois", tags: ["Shopify", "i18n", "CDN", "SEO"], coverLabel: "cover full · Zellige Store", defi: ["Zellige Store, cooperative d'artisans de Fes, vendait uniquement dans sa boutique physique. Le defi etait de creer une boutique en ligne mettant en valeur le savoir-faire artisanal marocain aupres d'une clientele internationale.", "L'enjeu : un site multilingue (FR/AR/EN), des paiements internationaux et une logistique de livraison integree."], solution: ["Nous avons deploye la boutique sur Shopify avec un theme sur mesure. Le multilingue gere automatiquement les devises et les traductions. Un CDN global assure des performances optimales depuis n'importe quel pays."], results: [{ value: "+300%", label: "de ventes en 6 mois" }, { value: "15", label: "pays livres" }, { value: "4.9", label: "avis clients moyen" }], images: ["page accueil", "fiche produit", "collection", "panier", "about"], testimonial: { quote: "Notre boutique en ligne a transforme notre activite. Nous touchons des clients du monde entier.", name: "Fatima Zahra", role: "Gerante · Zellige Store" }, relatedProjects: [{ title: "Atlas Market", client: "Projet client", category: "ecom", year: 2025, tags: ["Next.js"], slug: "/portfolio/atlas-market" }, { title: "Riad Booking", client: "Projet client", category: "web", year: 2023, tags: ["Astro"], slug: "/portfolio/riad-booking" }, { title: "Cap Spartel", client: "Projet client", category: "web", year: 2024, tags: ["Next.js"], slug: "/portfolio/cap-spartel" }] },
  { slug: "cap-spartel", title: "Cap Spartel", client: "Hotel Cap Spartel", category: "Site web", year: 2024, duration: "8 semaines", tags: ["Next.js", "Booking", "SEO", "CMS"], coverLabel: "cover full · Cap Spartel", defi: ["L'Hotel Cap Spartel dependait des plateformes de reservation pour sa visibilite. Il souhaitait un site vitrine qui convertisse les visiteurs en reservations directes, sans commission.", "L'enjeu : un site elegant refletant le standing de l'hotel, avec un moteur de reservation integre et des pages dediees pour chaque type de chambre."], solution: ["Nous avons cree le site avec Next.js et un CMS headless pour que l'equipe hoteliere puisse mettre a jour les photos et les offres speciales. Le systeme de reservation est connecte en temps reel au PMS de l'hotel via API."], results: [{ value: "+45%", label: "de reservations directes" }, { value: "0.6s", label: "temps de chargement" }, { value: "92", label: "score Lighthouse" }], images: ["page accueil", "chambres", "restaurant", "spa", "reservation"], testimonial: { quote: "Un site magnifique qui reflete parfaitement l'ame de notre etablissement. Les reservations directes ont explose.", name: "Mehdi Berrada", role: "Directeur · Hotel Cap Spartel" }, relatedProjects: [{ title: "Detroit Avocats", client: "Projet client", category: "web", year: 2024, tags: ["Astro"], slug: "/portfolio/detroit-avocats" }, { title: "Riad Booking", client: "Projet client", category: "web", year: 2023, tags: ["Astro"], slug: "/portfolio/riad-booking" }, { title: "Zellige Store", client: "Projet client", category: "ecom", year: 2024, tags: ["Shopify"], slug: "/portfolio/zellige-store" }] },
  { slug: "soukconnect", title: "SoukConnect", client: "SoukConnect SA", category: "Plateforme", year: 2025, duration: "6 mois", tags: ["React", "GraphQL", "Redis", "Docker"], coverLabel: "cover full · SoukConnect", defi: ["SoukConnect avait pour ambition de digitaliser le commerce B2B au Maroc en connectant grossistes et detaillants sur une plateforme unique. Le defi : gerer des catalogues de milliers de references avec des prix negociables.", "L'enjeu : une plateforme performante capable de gerer la negociation en temps reel et des workflows de commande complexes entre professionnels."], solution: ["L'architecture repose sur React en front-end, une API GraphQL pour des requetes optimisees et Redis pour le cache temps reel. Les workflows de commande integrent validation hierarchique et generation automatique des factures conformes a la legislation."], results: [{ value: "500+", label: "grossistes et detaillants inscrits" }, { value: "12k", label: "produits references" }, { value: "50ms", label: "temps de reponse moyen API" }], images: ["dashboard", "catalogue produits", "negociation", "commandes", "factures"], testimonial: { quote: "SoukConnect a digitalise notre chaine d'approvisionnement. Nous traitons 3 fois plus de commandes.", name: "Hassan Benjelloun", role: "DG · DistriMaroc" }, relatedProjects: [{ title: "Atlas Market", client: "Projet client", category: "ecom", year: 2025, tags: ["Next.js"], slug: "/portfolio/atlas-market" }, { title: "Mizan", client: "Projet client", category: "platform", year: 2025, tags: ["React"], slug: "/portfolio/mizan" }, { title: "Medina ERP", client: "Projet client", category: "erp", year: 2025, tags: ["Django"], slug: "/portfolio/medina-erp" }] },
  { slug: "foodtruck-ma", title: "FoodTruck MA", client: "FoodTruck MA SARL", category: "Mobile", year: 2023, duration: "4 mois", tags: ["Flutter", "Stripe", "Maps", "Firebase"], coverLabel: "cover full · FoodTruck MA", defi: ["FoodTruck MA gerait une flotte de 15 camions-restaurants a travers le nord du Maroc. Les commandes se faisaient par telephone, entraînant des erreurs, des temps d'attente et une experience client mediocre.", "L'enjeu : une application mobile permettant aux clients de commander et payer en ligne, de localiser les camions en temps reel et de recevoir des notifications quand leur commande est prete."], solution: ["Application Flutter avec geolocalisation en temps reel via Google Maps, paiement integre avec Stripe et notifications push Firebase. Un back-office Django permet aux gerants de gerer les menus, les prix et les emplacements des camions."], results: [{ value: "+80%", label: "de commandes en 3 mois" }, { value: "4.7", label: "etoiles sur le Play Store" }, { value: "-50%", label: "de temps d'attente client" }], images: ["accueil", "carte en direct", "menu", "paiement", "historique"], testimonial: { quote: "L'application a revolutionne notre facon de travailler. Les clients adorent voir les camions arriver en temps reel.", name: "Youssef Amrani", role: "Fondateur · FoodTruck MA" }, relatedProjects: [{ title: "RihlaGo", client: "Projet client", category: "mobile", year: 2024, tags: ["Flutter"], slug: "/portfolio/rihlago" }, { title: "Cap Spartel", client: "Projet client", category: "web", year: 2024, tags: ["Next.js"], slug: "/portfolio/cap-spartel" }, { title: "Zellige Store", client: "Projet client", category: "ecom", year: 2024, tags: ["Shopify"], slug: "/portfolio/zellige-store" }] },
  { slug: "riad-booking", title: "Riad Booking", client: "Riad Booking SARL", category: "Site web", year: 2023, duration: "10 semaines", tags: ["Astro", "Calendar", "i18n", "SEO"], coverLabel: "cover full · Riad Booking", defi: ["Riad Booking voulait creer une plateforme de reservation dediee aux riads de Marrakech, souvent absents des grandes plateformes internationales. Le defi : federer des proprietaires peu technophiles autour d'un outil simple.", "L'enjeu : un site multilingue (FR/AR/EN) avec un calendrier de reservation intuitif, un back-office minimal pour les proprietaires et un systeme de paiement securise."], solution: ["Site Astro avec rendu statique pour des performances maximales. Le calendrier utilise une API sur mesure avec blocage automatique des dates. Interface d'administration simplifiee en 3 ecrans pour les proprietaires."], results: [{ value: "80+", label: "riads references" }, { value: "3k", label: "nuits reservees par mois" }, { value: "100/100", label: "score Lighthouse" }], images: ["accueil", "recherche", "fiche riad", "calendrier", "admin"], testimonial: { quote: "Un outil simple et efficace. Mes reservations ont double depuis que j'ai rejoint la plateforme.", name: "Latifa El Amrani", role: "Proprietaire · Riad Zohra" }, relatedProjects: [{ title: "Cap Spartel", client: "Projet client", category: "web", year: 2024, tags: ["Next.js"], slug: "/portfolio/cap-spartel" }, { title: "Detroit Avocats", client: "Projet client", category: "web", year: 2024, tags: ["Astro"], slug: "/portfolio/detroit-avocats" }, { title: "Zellige Store", client: "Projet client", category: "ecom", year: 2024, tags: ["Shopify"], slug: "/portfolio/zellige-store" }] },
  { slug: "gestapro", title: "GestaPro", client: "GestaPro SA", category: "ERP", year: 2024, duration: "7 mois", tags: ["Django", "PostgreSQL", "BI", "Celery"], coverLabel: "cover full · GestaPro", defi: ["GestaPro cible les PME marocaines qui gerent leur facturation avec des outils bureautiques. Le defi : proposer un ERP accessible, modulable et conforme a la legislation fiscale marocaine, sans la complexite des grands ERP.", "L'enjeu : automatiser la generation des factures, le suivi des paiements et les declarations de TVA tout en restant simple a utiliser."], solution: ["ERP sur Django avec modules independants (facturation, stock, clients, reporting). Les donnees fiscales sont mises a jour automatiquement selon les baremes officiels. Un assistant integre guide les nouveaux utilisateurs."], results: [{ value: "150+", label: "PME clientes" }, { value: "5min", label: "pour generer une facture" }, { value: "-70%", label: "d'erreurs comptables" }], images: ["dashboard", "facturation", "stocks", "clients", "rapports"], testimonial: { quote: "Un ERP qui s'adapte a notre metier, pas l'inverse. L'equipe a adopte l'outil en une semaine.", name: "Nadia Cherkaoui", role: "Gerante · Menuiserie Moderne" }, relatedProjects: [{ title: "Medina ERP", client: "Projet client", category: "erp", year: 2025, tags: ["Django"], slug: "/portfolio/medina-erp" }, { title: "Mizan", client: "Projet client", category: "platform", year: 2025, tags: ["React"], slug: "/portfolio/mizan" }, { title: "SoukConnect", client: "Projet client", category: "platform", year: 2025, tags: ["GraphQL"], slug: "/portfolio/soukconnect" }] },
  { slug: "edutanger", title: "EduTanger", client: "EduTanger Foundation", category: "Plateforme", year: 2025, duration: "5 mois", tags: ["Next.js", "Prisma", "Video", "AWS"], coverLabel: "cover full · EduTanger", defi: ["EduTanger, une fondation educative basee a Tanger, avait besoin d'une plateforme LMS pour dispenser des cours en ligne a des eleves du secondaire dans tout le nord du Maroc. Les contraintes : faibles connexions internet et diversite des appareils.", "L'enjeu : une plateforme legere et accessible, avec des videos optimisees, des quiz interactifs et un suivi de progression pour chaque eleve."], solution: ["Plateforme Next.js avec streaming video adaptatif via HLS. Les cours sont consultables hors-ligne via Service Workers. Un tableau de bord enseignant permet de suivre la progression de chaque classe et d'identifier les eleves en difficulte."], results: [{ value: "5k", label: "eleves inscrits" }, { value: "200+", label: "cours disponibles" }, { value: "85%", label: "de taux de completion" }], images: ["accueil", "catalogue cours", "lecture video", "quiz", "dashboard prof"], testimonial: { quote: "Une plateforme adaptee a notre realite. Les eleves en zone rurale peuvent enfin suivre des cours de qualite.", name: "Pr. Amine Tazi", role: "Directeur · EduTanger" }, relatedProjects: [{ title: "Mizan", client: "Projet client", category: "platform", year: 2025, tags: ["React"], slug: "/portfolio/mizan" }, { title: "Atlas Market", client: "Projet client", category: "ecom", year: 2025, tags: ["Next.js"], slug: "/portfolio/atlas-market" }, { title: "Medina ERP", client: "Projet client", category: "erp", year: 2025, tags: ["Django"], slug: "/portfolio/medina-erp" }] },
];

/* EN */
const enProjects: ProjectData[] = [
  { title: "Atlas Market", client: "Marketplace · Casablanca", category: "ecom", year: 2025, tags: ["Next.js", "Stripe", "Sanity"], slug: "/portfolio/atlas-market" },
  { title: "Medina ERP", client: "Industrial mgmt · Tangier", category: "erp", year: 2025, tags: ["Django", "PostgreSQL", "Docker"], slug: "/portfolio/medina-erp" },
  { title: "RihlaGo", client: "Travel app · Morocco", category: "mobile", year: 2024, tags: ["Flutter", "Firebase", "Maps"], slug: "/portfolio/rihlago" },
  { title: "Detroit Avocats", client: "Law firm · Tangier", category: "web", year: 2024, tags: ["Astro", "CMS", "SEO"], slug: "/portfolio/detroit-avocats" },
  { title: "Mizan", client: "Accounting SaaS · Rabat", category: "platform", year: 2025, tags: ["React", "Node.js", "AWS"], slug: "/portfolio/mizan" },
  { title: "Zellige Store", client: "Craft online · Fez", category: "ecom", year: 2024, tags: ["Shopify", "i18n", "CDN"], slug: "/portfolio/zellige-store" },
  { title: "Cap Spartel", client: "Hospitality · Tangier", category: "web", year: 2024, tags: ["Next.js", "Booking", "SEO"], slug: "/portfolio/cap-spartel" },
  { title: "SoukConnect", client: "B2B Marketplace · Morocco", category: "platform", year: 2025, tags: ["React", "GraphQL", "Redis"], slug: "/portfolio/soukconnect" },
  { title: "FoodTruck MA", client: "Mobile ordering · Tetouan", category: "mobile", year: 2023, tags: ["Flutter", "Stripe", "Maps"], slug: "/portfolio/foodtruck-ma" },
  { title: "Riad Booking", client: "Riad bookings · Marrakech", category: "web", year: 2023, tags: ["Astro", "Calendar", "i18n"], slug: "/portfolio/riad-booking" },
  { title: "GestaPro", client: "SME invoicing · Agadir", category: "erp", year: 2024, tags: ["Django", "PostgreSQL", "BI"], slug: "/portfolio/gestapro" },
  { title: "EduTanger", client: "E-learning LMS · Tangier", category: "platform", year: 2025, tags: ["Next.js", "Prisma", "Video"], slug: "/portfolio/edutanger" },
];

/* --- EN/AR details inherit most from FR, override only localized text --- */
const enDetails: ProjectDetail[] = frDetails.map((d) => {
  const overrides: Record<string, Partial<ProjectDetail>> = {
    "atlas-market": { client: "Atlas Retail Group", category: "E-commerce", duration: "4 months", tags: ["Next.js", "Stripe", "Sanity", "PostgreSQL", "Vercel"], defi: ["Atlas Retail Group wanted to unify three brands under a single marketplace, capable of handling thousands of SKUs, multiple vendors and traffic spikes during sales periods. The old site was slow and hard to maintain, hindering growth.", "The challenge: deliver a fast, multilingual (FR/AR) shopping experience and a back-office allowing teams to manage the catalog autonomously."], solution: ["We rebuilt the platform on Next.js with a headless CMS (Sanity) and Stripe payments. Server-side rendering and a global CDN guarantee sub-second load times worldwide."], results: [{ value: "+40%", label: "online sales in 3 months" }, { value: "0.8s", label: "average load time" }, { value: "3\u21921", label: "brands unified into one marketplace" }], testimonial: { quote: "A masterpiece. The site is fast, beautiful and our sales jumped 40% in three months.", name: "Yasmine Bennani", role: "CEO · Atlas Market" } },
    "medina-erp": { category: "ERP", duration: "6 months", tags: ["Django", "PostgreSQL", "Docker", "Redis", "Celery"], defi: ["Medina Industries managed inventory, billing and HR with Excel spreadsheets and disconnected tools. Data entry errors were frequent and reporting took days.", "The challenge: centralize all operations in a single ERP, accessible from the factory and head office, with real-time dashboards."], solution: ["We developed a custom ERP with Django and PostgreSQL. The modular architecture allows new features to be added without impacting existing ones. CSV imports/exports automate partner exchanges."], results: [{ value: "-60%", label: "data entry errors" }, { value: "3x", label: "faster monthly reports" }, { value: "100%", label: "centralized processes" }], testimonial: { quote: "Our ERP transformed our management. Everything is centralized, smooth and finally understandable.", name: "Karim El Fassi", role: "Director · Medina Industries" } },
  };
  const o = overrides[d.slug] || {};
  return { ...d, ...o };
});

const arDetails: ProjectDetail[] = frDetails.map((d) => {
  const overrides: Record<string, Partial<ProjectDetail>> = {
    "atlas-market": { category: "تجارة إلكترونية", duration: "4 أشهر", defi: ["أرادت مجموعة أطلس للتجزئة توحيد ثلاث علامات تجارية تحت سوق إلكترونية واحدة قادرة على إدارة آلاف المنتجات وبائعين متعددين وذروات حركة المرور خلال فترات التخفيضات.", "التحدي: تقديم تجربة تسوق سريعة متعددة اللغات (الفرنسية/العربية) ومكتب خلفي يمكّن الفرق من إدارة الكتالوج بشكل مستقل."], solution: ["أعدنا بناء المنصة على Next.js مع نظام إدارة محتوى بدون رأس (Sanity) ومدفوعات Stripe. يضمن التصيير من جانب الخادم وشبكة CDN عالمية أوقات تحميل أقل من ثانية في جميع أنحاء العالم."], results: [{ value: "+40%", label: "زيادة المبيعات الإلكترونية في 3 أشهر" }, { value: "0.8s", label: "متوسط وقت التحميل" }, { value: "3\u21921", label: "علامات تجارية موحدة في سوق واحدة" }], testimonial: { quote: "عمل متقن. الموقع سريع وجميل وزادت مبيعاتنا بنسبة 40% في ثلاثة أشهر.", name: "ياسمين بناني", role: "المديرة التنفيذية · أطلس ماركت" } },
    "medina-erp": { category: "تخطيط موارد", duration: "6 أشهر", defi: ["كانت شركة مدينا للصناعات تدير المخزون والفواتير والموارد البشرية باستخدام جداول إكسل وأدوات منفصلة. كانت أخطاء الإدخال متكررة والتقارير تستغرق أياماً.", "التحدي: مركزة جميع العمليات في نظام تخطيط موارد واحد، متاح من المصنع والمقر الرئيسي، مع لوحات معلومات في الوقت الفعلي."], solution: ["طورنا نظام تخطيط موارد مخصص باستخدام Django وPostgreSQL. تتيح الهندسة المعيارية إضافة ميزات جديدة دون التأثير على الموجود. تعمل عمليات الاستيراد/التصدير CSV على أتمتة التبادلات مع الشركاء."], results: [{ value: "-60%", label: "من أخطاء الإدخال" }, { value: "3x", label: "أسرع في التقارير الشهرية" }, { value: "100%", label: "عمليات مركزية" }], testimonial: { quote: "حوّل نظام تخطيط الموارد إدارتنا. كل شيء مركزي وسلس ومفهوم أخيراً.", name: "كريم الفاسي", role: "مدير · مدينا للصناعات" } },
  };
  const o = overrides[d.slug] || {};
  return { ...d, ...o };
});

function buildPortfolioPageData(locale: string): PortfolioPageData {
  const l10n: Record<string, { eyebrow: string; title: string; subtitle: string; lastCrumb: string; filters: { key: string; label: string }[]; loadMore: string }> = {
    en: { eyebrow: "PORTFOLIO", title: "Our work", subtitle: "A selection of projects delivered for clients in Morocco and abroad.", lastCrumb: "Portfolio", filters: [{ key: "all", label: "All" }, { key: "web", label: "Websites" }, { key: "ecom", label: "E-commerce" }, { key: "platform", label: "Platforms" }, { key: "erp", label: "ERP" }, { key: "mobile", label: "Mobile" }], loadMore: "Load more projects" },
    fr: { eyebrow: "PORTFOLIO", title: "Nos realisations", subtitle: "Une selection de projets livres pour des clients au Maroc et a l'international.", lastCrumb: "Portfolio", filters: [{ key: "all", label: "Tous" }, { key: "web", label: "Sites web" }, { key: "ecom", label: "E-commerce" }, { key: "platform", label: "Plateformes" }, { key: "erp", label: "ERP" }, { key: "mobile", label: "Mobile" }], loadMore: "Charger plus de projets" },
    ar: { eyebrow: "المشاريع", title: "أعمالنا", subtitle: "مجموعة مختارة من المشاريع المسلمة لعملاء في المغرب وخارجه.", lastCrumb: "المشاريع", filters: [{ key: "all", label: "الكل" }, { key: "web", label: "مواقع" }, { key: "ecom", label: "متاجر" }, { key: "platform", label: "منصات" }, { key: "erp", label: "ERP" }, { key: "mobile", label: "جوال" }], loadMore: "تحميل المزيد من المشاريع" },
  };
  const t = l10n[locale] || l10n.fr;
  return {
    ...t,
    lastBreadcrumb: t.lastCrumb,
    projects: locale === "en" ? enProjects : locale === "ar" ? enProjects : frProjects,
    details: locale === "en" ? enDetails : locale === "ar" ? arDetails : frDetails,
  };
}

export const fallbackPortfolioData: Record<string, PortfolioPageData> = {
  en: buildPortfolioPageData("en"),
  fr: buildPortfolioPageData("fr"),
  ar: buildPortfolioPageData("ar"),
};
