# Generated by Django 5.1.15 on 2026-06-20 16:08

import apps.core.mixins
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='get_title', unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('website', 'Site web'), ('ecommerce', 'E-commerce'), ('platform', 'Plateforme'), ('erp', 'ERP'), ('mobile', 'Mobile')], default='website', max_length=20)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='services.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-year', 'order'],
            },
            bases=(models.Model, apps.core.mixins.TranslatableMixin),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('short_description', models.TextField(max_length=300)),
                ('long_description', models.TextField(blank=True, default='')),
                ('client_testimonial', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=120)),
                ('meta_description', models.TextField(blank=True, default='', max_length=320)),
                ('auto_translated', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Translation',
                'verbose_name_plural': 'Project Translations',
                'unique_together': {('project', 'language')},
            },
        ),
    ]
